name = "simracing-mozacare"
main = "_worker.js"
compatibility_date = "2025-04-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "404-page"

[[d1_databases]]
binding = "DB"
database_name = "simracing_orders"
database_id = "8188a701-2eba-45e9-b46f-b278bab1b5d5"
